--- #Sample Playbook Netapp 
- hosts: localhost
  gather_facts: no
  connection: local
  vars: 
    netapp_hostname: 172.21.221.205
    netapp_username: admin
    netapp_password: netapp!123


  tasks:

    - name: Create SVM 
      na_ontap_svm:
         state: present
         name: 
         root_volume:
         root_volume_aggregate:
         root_volume_security_style: unix 
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"

    - name: Create SVM-1
      na_ontap_svm:
         state: present
         name: 
         root_volume:
         root_volume_aggregate:
         root_volume_security_style:
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"


    - name: Create ifgrp
      na_ontap_net_ifgrp:
         state: present
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"
         hostname: "{{ netapp_hostname }}"
         distribution_ip: ip
         name: a0c
         port: e0d
         mode: multimode
         node: 
 
    - name: Create ifgrp-1
      na_ontap_net_ifgrp: 
         state: present
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"
         hostname: "{{ netapp_hostname }}" 
         distribution_ip: ip
         name:
         port:
         mode:
         node: 

    - name: Create LIF-MGMT 
      na_ontap_interface: 
         state: present
         interface_name: 
         home_port:
         home_node:
         role: data
         protocols: none
         admin_status: up
         is_auto_revert: true
         address:
         netmask: 
         vserver: 
         failover_policy: local-only
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"

    - name: Create LIF-MGMT-1 
      na_ontap_interface:
         state: present
         interface_name:
         home_port:
         home_node:
         role:
         protocols: none
         admin_status: up
         is_auto_revert: true
         address:
         netmask: 
         vserver: 
         failover_policy: local-only
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"

    - name: Create LIF-CIFS
      na_ontap_interface: 
         state: present
         interface_name: 
         home_port:
         home_node: 
         role: 
         protocols: cifs
         admin_status: up
         is_auto_revert: true
         address:
         netmask:
         vserver: 
         failover_policy: local-only
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}" 

    - name: Create LIF-CIFS-1
      na_ontap_interface: 
         state: present
         interface_name: 
         home_port: 
         home_node:
         role:
         protocols: cifs
         admin_status: up
         is_auto_revert: true
         address: 
         netmask:
         vserver: 
         failover_policy: local-only
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"

    - name: Create LIF-NFS
      na_ontap_interface:
         state: present
         interface_name:
         home_port:
         home_node:
         role:
         protocols: nfs
         admin_status: up
         is_auto_revert: true
         address: 
         netmask:
         vserver: 
         failover_policy: local-only
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"

    - name: Create LIF-NFS-1
      na_ontap_interface:
         state: present
         interface_name: 
         home_port: 
         home_node: 
         role:
         protocols: nfs
         admin_status: up
         is_auto_revert: true
         address: 
         netmask:
         vserver:
         failover_policy: local-only
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"

    - name: Create LIF-VSCAN 
      na_ontap_interface:
         state: present
         interface_name: 
         home_port: 
         home_node: 
         role: 
         protocols: cifs
         admin_status: up
         is_auto_revert: true
         address:
         netmask:
         vserver: 
         failover_policy: local-only
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"

    - name: Create LIF-VSCAN-1
      na_ontap_interface:
         state: present
         interface_name:
         home_port:
         home_node:
         role: 
         protocols: cifs
         admin_status: up
         is_auto_revert: true
         address:
         netmask:
         vserver: 
         failover_policy: local-only
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"

    - name: Create Export Policy
      na_ontap_export_policy: 
         state: present
         name: 
         vserver: 
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"

    - name: Create Export Policy-1
      na_ontap_export_policy:
         state: present
         name: 
         vserver: 
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"

    - name: Create Export Policy Rule 
      na_ontap_export_policy_rule:
         state: present
         policy_name: 
         vserver: 
         client_match:
         ro_rule: sys
         rw_rule: sys
         protocol: any 
         super_user_security: sys
         allow_suid: true
         rule_index:  
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}" 

    - name: Create Export Policy Rule-1
      na_ontap_export_policy_rule: 
         state: present 
         policy_name: 
         vserver:
         client_match:
         ro_rule: sys
         rw_rule: sys 
         protocol: any 
         super_user_security: sys
         allow_suid: true
         rule_index: 
         hostname: "{{ netapp_hostname }}"
         username: "{{ nteapp_username }}"
         password: "{{ netapp_password }}"

    - name: Create Job Schedule
      na_ontap_job_schedule: 
         state: present
         name: 
         job_minutes:
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"

    - name: Create Job Schedule-1
      na_ontap_job_schedule:
         state: present
         name:
         job_minutes: 
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}" 

    - name: Create FlexVols
      na_ontap_volume:
         state: present 
         name: 
         aggregate_name: 
         size:
         size_unit: 
         policy: 
         junction_path:
         infinite: false
         volume_security_style: 
         vserver: 
         space_guarantee: none
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"
 
    - name: Create FlexVols-1
      na_ontap_volume:
         state: present
         name:
         aggregate_name: 
         size:
         size_unit:
         policy:
         junction_path:
         infinite: false
         volume_secutiry_style:
         vserver:
         space_guarantee: none
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"
   
    - name: Create CIFS-Share 
      na_ontap_cifs: 
         state: present
         share_name: 
         path: 
         vserver:
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"

    - name: Create CIFS-Share-1
      na_ontap_cifs:
         state: present 
         share_name:
         path: 
         vserver: 
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"

    - name: Create CIFS-ACL
      na_ontap_cifs_acl:
         state: present
         share_name:
         user_or_group:
         permission:
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"

    - name: Create CIFS-ACL-1
      na_ontap_cifs_acl:
         state: present
         share_name: 
         user_or_group:
         permission:
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{{ netapp_password }}"

    - name: Configure NTP 
      na_ontap_ntp: 
         state: present
         version: auto 
         server_name: 
         hostname: "{{ netapp_hostname }}"
         username: "{{ netapp_username }}"
         password: "{[ netapp_password }}"
  
   
          
  


   



  
           
       
          

          

  
          
           
